version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    networks:
      - hadoop
    environment:
      - CLUSTER_NAME=test
    volumes:
      - namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"
      - "8020:8020"
    deploy:
      placement:
        constraints: [node.role == manager]
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    networks:
      - hadoop
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
    volumes:
      - datanode:/hadoop/dfs/data
    ports:
      - "9864:9864"
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints: [node.role != manager]

  spark-master:
    image: bitnami/spark:latest
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - shared-workspace:/opt/workspace
      # - ./hadoop-conf:/opt/bitnami/spark/hadoop/conf
    networks:
      - hadoop
    deploy:
      placement:
        constraints: [node.role == manager]

  jupyterlab:
    image: jupyter/all-spark-notebook:latest
    volumes:
      - ./hadoop-conf:/opt/bitnami/spark/hadoop/conf
    ports:
      - "8888:8888"
    networks:
      - hadoop
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  shared-workspace:
  namenode:
  datanode:

networks:
  hadoop:
    driver: bridge