version: '3'

volumes:
  shared-workspace:
    driver: local
  namenode-data:
    driver: local

services:
  jupyterlab:
    container_name: jupyterlab
    image: jupyter/base-notebook:python-3.8.3
    volumes:
      - shared-workspace:/opt/workspace
    network_mode: "host"

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://192.168.2.107:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    network_mode: "host"
    volumes:
      - shared-workspace:/opt/workspace
    deploy:
      placement:
        constraints:
          - node.hostname == 192.168.2.107

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    environment:
      - HDFS_CONF_dfs_namenode_http_bind_host=0.0.0.0
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://127.0.0.1:8020
      - HDFS_CONF_dfs_namenode_rpc_address=127.0.0.1:8020
      - HDFS_CONF_dfs_namenode_http_address=0.0.0.0:50070
    volumes:
      - namenode-data:/hadoop/dfs/name
    network_mode: "host"
    deploy:
      placement:
        constraints:
          - node.hostname == 192.168.2.107

