version: '3.8'

services:
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - shared-workspace:/opt/workspace
    networks:
      - hadoop
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints: [node.role != manager]
  spark-worker:
    image: bitnami/spark
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - hadoop
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints: [node.role != manager]

volumes:
  datanode:

networks:
  hadoop:
    driver: bridge